:bug: break circular dependecies
colorlog must be "hide" inside function
it cannot be import at top level neither  referenced in function
signature.
because setup import __init__ to get __version__
so logger_set_level is defined
if level is colorlog.logging.logging.WARNING
that mean that colorlog must be already installed
otherwise an error occured during pip install
NameError: name 'colorlog' is not defined